class HomeState {}
class InitHomeScreen extends HomeState{}
class DoctorPatientLoading extends HomeState{}
class DoctorPatientSuccess extends HomeState{}
class DoctorPatientError extends HomeState{}
class AddPatientError extends HomeState{}
class AddPatientLoading extends HomeState{}
class AddPatientSuccess extends HomeState{}
class DataSuccess extends HomeState{}
class DataError extends HomeState{}
class ClearTextSuccess extends HomeState{}
class ShowPatientSuccess extends HomeState{}
class ShowPatientError extends HomeState{}
class ShowPatientLoading extends HomeState{}
class DeleteProductLoading extends HomeState{}
class DeleteProductSuccess extends HomeState{}
class DeleteProductError extends HomeState{}
class UpdatePatientLoading extends HomeState{}
class UpdatePatientSuccess extends HomeState{}
class UpdatePatientError extends HomeState{}
class OnSelectSuccess extends HomeState{}